### ISSUE TITLE
Vivofit support

### ISSUE THREAD

**Issue by shookees** [Tigge/Garmin-Forerunner-610-Extractor#99] opened 2014-06-24 18:02 UTC
It seems to be partly working with vivofit. The workout first workout file is downloaded the right way, although I'm not sure about the second (1989 yr.) file
Here's a paste of the log, maybe I should just add an exception for this file?
http://pastebin.com/KhfSjHWG

**Comment by Tigge** [comment] 2015-01-03 15:10
Hopefully this will work better with #120. Closing. Re-open if it still fails.

**Closed by Tigge** 2015-01-03 15:10 UTC

**Comment by balu-** [comment] 2015-03-29 13:36
seems like #120 (or 32aa009ab45a566a2c3aa16412756630ea64415b in particular) 
make antfs-cli redownload every single .fit file on the watch on every snyc? 

Not familiar with python code, i only observed the behavior of the script, and by reverting the commit i got the old behavoir where only new files are transmitted.
Is there a reason to transfer all the files everytime?

**Comment by Tigge** [comment] 2015-03-31 13:43
There should be no change in behavior with this commit. If it doesn't work anymore there is probably a bug in there somewhere. I'm not able to reproduce this on my system.

**Comment by balu-** [comment] 2015-04-05 23:38
my bad
redownload is triggerd by this change (as the commit message says :flushed: ) https://github.com/Tigge/antfs-cli/commit/da76e054ea1618a805c4e34789479dfd35021929
